---
title: "Homework 1: Thinking About Data"
subtitle: "BEE 4850"
date: "02-06-2026"
author: "Avinash Aravind, aa2476"
format:
    html:        
        warning: true
        error: true
        fig-format: svg
    pdf:
        warning: true
        error: true
        keep-tex: true
        fig-pos: "h"
        toc: true
        toc-depth: 3
        toc-title: Contents
        fig-format: svg    
        include-in-header: 
            text: |
                \usepackage{fvextra}
                \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
        include-before-body:
            text: |
                \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
                showspaces = false,
                showtabs = false,
                breaksymbolleft={},
                breaklines
                % Note: setting commandchars=\\\{\} here will cause an error 
                }
        margin-bottom: "30mm"
    ipynb:
        warning: true
        error: true
engine: julia
julia:
    exeflags: ["+1.11.5"]
format-links: [pdf]
freeze: false
---
::: {.callout-note}
All of the code used in this homework is accessible in the hw01.qmd file in my GitHub repository.
:::

```{julia}
#| echo: false
#| output: false

import Pkg
Pkg.activate(@__DIR__)
Pkg.instantiate()
```


```{julia}
#| output: false
#| echo: false

using Random # random number generation and seed-setting
using DataFrames # tabular data structure
using CSVFiles # reads/writes .csv files
using Distributions # interface to work with probability distributions
using Plots # plotting library
using StatsBase # statistical quantities like mean, median, etc
using StatsPlots # some additional statistical plotting tools
```

::: {.cell .markdown}
# Problem 1 (7 points)
:::

```{julia}
#| output: false
#| echo: false
data = DataFrame(load("data/bites.csv")) # load data into DataFrame

# print data variable (semi-colon suppresses echoed output in Julia, which in this case would duplicate the output)
@show data; 
```

```{julia}
#| echo: false
#| output: false
# split data into vectors of bites for each group
beer = data[data.group .== "beer", :bites]
water = data[data.group .== "water", :bites]

observed_difference = mean(beer) - mean(water)
@show observed_difference;
```

### Problem 1.1

_Conduct the above procedure to generate 50,000 simulated datasets under the skeptic's hypothesis. Plot a histogram of the results and add a dashed vertical line to show the experimental difference._

```{julia}
#| echo: false
#| label: fig-mosquito-hist
#| fig-cap: "Histogram of Mean Differences for 50000 shuffled simulations of mosquito bite data for beer vs. water drinkers."

sim_diffs = []
for i in 1:50000
    biteshuffle = shuffle(data[!, :bites])
    datashuffle = DataFrame(group=data[!, :group], bites=biteshuffle)

    beer = datashuffle[datashuffle.group .== "beer", :bites]
    water = datashuffle[datashuffle.group .== "water", :bites]

    shuffle_difference = mean(beer) - mean(water)
    append!(sim_diffs, [shuffle_difference])
end

plot(sim_diffs, st=:histogram, label="Shuffled Differences", xlabel="Beer-Water Mean Difference", ylabel="Count", title="Shuffle Simulations of Mosquito Bites")
plot!([observed_difference], st=:vline , ls=:dash, label="Observed Difference")
```

### Problem 1.2

_Draw conclusions about the plausibility of the skeptic's hypothesis that there is no difference between groups. Feel free to use any quantitative or qualitative assessments of your simulations and the observed difference._

Based on the simulation results, the skeptic's hypothesis does not appear very plausible. As would be expected from a random shuffle, the difference between the randomized "beer" and "water" category means is centered around zero, with the majority of simulations having a mean difference between -2 and 2. However, the observed difference is well over 4, and there are only a very small number of shuffles with a mean difference that large. It is unlikely that such a large difference would be drawn from this distribution of random simulations, suggesting that there is a difference in mosquito bites for beer drinkers versus water drinkers.


# Problem 2 (5 points)

### Problem 2.1 

::: {.cell .markdown}

_Load the dataset and compute the following summary statistics for each column (you can do this using built-in functions as available in the language you are using):_

1. _Minimum, 25th percentile, median, 75th percentile, and maximum;_
2. _Mean;_
3. _Number of missing data entries (`NA`s)._

_What are the units for the temperatures? Explain why there are so many negative values for the pollution variables._
:::

```{julia}
#| echo: false
chicago = DataFrame(load("data/chicago.csv"))

describe(chicago, :min, :q25, :median, :q75,:max, :mean, :nmissing)
```
::: {.cell .markdown}

The temperatures are in units of degrees Fahrenheit, ranging from approximately -15°F to approximately 90°F, a typical range for the Midwestern United States. 
I was originally confused as to why there were negative values for the pollution variables, so I did a bit of online searching and found the National Ambient Air Quality Standards[^1] from the U.S. Environmental Protection Agency. These standards set reference values for what "acceptable" values for air pollutants are based on public health research. Looking at the values for this standard, it seems the Chicago pollution measurements are reported in terms of their difference to this standard, with negative values below the standard and positive values above the standard.
:::

[^1]: <https://www.epa.gov/criteria-air-pollutants/naaqs-table>

```{=latex}
\newpage
```

### Problem 2.2

_Plot the number of deaths versus the time (convert the time to the calendar date). Describe any patterns that you see._

```{julia}
#| echo: false 
#| label: fig-chicago-deaths-time
#| fig-cap: "Plot of daily deaths in Chicago from 01-01-1987 to 12-31-2000."
using Dates
ndays = length(chicago.time)
dates = []
for i = 0:ndays-1
    newdate = [Date("1987-01-01", dateformat"y-m-d")+Dates.Day(i)]
    append!(dates, newdate)
end

plot(dates, chicago.death, st=:line, label="Daily Deaths", xlabel="Date", ylabel="Deaths", title="Chicago Daily Deaths, 1987-2000")
```

::: {.cell .markdown}
There does not appear to be any significant increase or decrease in the number of deaths in Chicago throughout the 13-year period. Typically, the number of daily deaths appears to peak in the winter, decrease through the spring, reach a minimum in the summer, and then increases through the fall. Apart from a small number days, including one day with a daily total of over 400 deaths, the daily counts typically range in the low 100s, which matches what we see from the summary statistics with a q25 of 105 and a q75 of 124.
:::

```{=latex}
\newpage
```
### Problem 2.3

_Plot the number of deaths versus the temperature. Describe any patterns that you see._
```{julia}
#| echo: false 
#| label: fig-chicago-deaths-temp
#| fig-cap: "Scatterplot of daily deaths and temperature in Chicago from 1987 to 2000."

plot(chicago.tmpd, chicago.death, st=:scatter, label="Daily Deaths", xlabel="Temperature (°F)", ylabel="Deaths", title="Chicago Deaths vs. Temperature")
```

There is a slightly negative correlation between temperature and number of deaths, with almost no days having less than 100 deaths when the temperature is below 20°F but many such days when the temperature is above 60°F. However, the difference between daily deaths when the temperature is below freezing versus very warm does not appear to be large. However, the high outliers in terms of number of deaths all occur when the average daily temperature was extremely high, which suggested to me that this was associated with some kind of heat wave. Matching with the dates in @fig-chicago-deaths-time, I was able to find information about the July 1995 Chicago Heat Wave, which lead to over 500 deaths in the city of Chicago and caused heat index values of above 115°F.[^2]

[^2]: <https://www.weather.gov/lot/1995_HeatWave>

```{=latex}
\newpage
```

### Problem 2.4

_What do you think has a clearer influence on the number of deaths: date or temperature?_  

I think date has a clearer influence on the number of deaths. While there does appear to be a slight negative correlation in the temperature data (@fig-chicago-deaths-temp), the magnitude of the influence is difficult to discern. However, in @fig-chicago-deaths-time, the oscillating pattern of increasing and decreasing deaths with season is easily evident, and so I believe the date can be more easily used to understand the number of deaths.

```{=latex}
\newpage
```

# Problem 3 (3 points)

### Problem 3.1

::: {.cell .markdown}
_Load the data file and produce the following summary statistics for the day (not the date) of full flowering (you can do this using built-in functions as available in the language you are using):_

1. _Minimum, 25th percentile, median, 75th percentile, and maximum;_
2. _Mean;_
3. _Number of missing data entries (`NA`s)._

_Why would it not make sense to calculate these summary statistics for the date column?_
:::

```{julia}
#| echo: false
blossoms = DataFrame(load("data/kyoto.csv"))

describe(blossoms, :min, :q25, :median, :q75,:max, :mean, :nmissing)
```

Since each month in the Gregorian calendar only has 28, 29, 30, or 31 days, the values in the date column do not come from a continuous set of integers from 101 to 1299 but instead 101 to 131 before a jump to 201. As such, summary statistics may not accurately summarize the dates of bloom.

```{=latex}
\newpage
```

### Problem 3.2

_Plot the day of flowering against the year. Add horizontal lines showing the mean date of flowering as well as the 25th and 75th percentiles.  Do you see any trends or patterns in the data?_

```{julia}
#| echo: false 
#| label: fig-bloom-yearly
#| fig-cap: "Scatterplot of cherry blossom flowering date verus year in Kyoto from A.D. 801 to 2015. Horizontal dashed lines indicate 25th (red) and 75th (green) percentiles."

plot(blossoms."Year.AD", blossoms."Flowering.DOY", st=:scatter, legend=false, xlabel="Year (A.D.)", ylabel="Flowering Date (Days from 01-01)", title="Kyoto Cherry Blossom Dates")
plot!(blossoms."Year.AD", [100], st=:hline, ls=:dash)
plot!(blossoms."Year.AD", [109], st=:hline, ls=:dash)
```

Overall, there is not much of a pattern or trend in the data, with a variety of early or late blooms throughout the historical period. However, at the very end of the data, the range of blossom dates appears to narrow significanatly, with fewer very early and very late blooms. There also appears to be a bit of a negative trend in this period, towards an earlier mean flowering date. Towards the very end of the period, many more flowering dates are below the 25th percentile, and almost none are above the 75th percentile.

```{=latex}
\newpage
```

# Problem 4 (5 points)

### Problem 4.1

_Create a generative model for the grant-selection procedure under the null assumption of no correlation between rigor and impact. You can sample rigor and impact scores directly from $\text{Normal}(0, 1)$.  Generate 1,000 datasets using this model and flag the proposals which would be funded in each. Plot a histogram of the correlations between rigor and data for (a) the funded proposals and (b) the overall pool. What do you observe?_

```{julia}
#| echo: false
#| output: false
all_cors = []
funded_cors = []

for i = 1:1000
    proposals = DataFrame(rigor=randn(200), impact=randn(200))
    proposals[!, :score] = proposals.rigor+proposals.impact
    q90 = percentile(proposals.score, 90)
    proposals[!, :accepted] = proposals.score .>= [q90]
    correlation_all = cor(Matrix(proposals[:,1:2]))[1,2]
    correlation_accepted = cor(Matrix(proposals[proposals.accepted .== true, 1:2]))[1,2]

    append!(all_cors, [correlation_all])
    append!(funded_cors, [correlation_accepted])
end
```

```{julia}
#| echo: false 
#| label: fig-correlation-accepted
#| fig-cap: "Histogram of Rigor-Impact Correlations for 1000 simulated grant proposals of 200 applications each, with only the funded applications (top 10%) included."
plot(funded_cors, st=:histogram, legend=false, xlabel="Rigor/Impact Correlation", ylabel="Count", title="Rigor/Impact Correlations for Funded Proposals")
```

```{julia}
#| echo: false 
#| label: fig-correlation-all
#| fig-cap: "Histogram of Rigor-Impact Correlations for 1000 simulated grant proposals of 200 applications each. All applications included."
plot(all_cors, st=:histogram, legend=false, xlabel="Rigor/Impact Correlation", ylabel="Count", title="Rigor/Impact Correlations for All Proposals")
```

Among the funded applications in @fig-correlation-accepted, all have a negative rigor-impact correlation, with the peak of the sample distribution at around -0.8, thus confirming the researcher's findings of a negative correlation for the funded proposals. However, the researcher's claim was that **all** high-impact proposals were necessarily less rigorous, which would imply a similar negative correlation among all proposals. The sample distribution in @fig-correlation-all is nearly zero-centered and is visually similar to the Normal distribution, suggesting there is no strong correlation between rigor and impact among the general pool of proposals, suggesting the researcher's claim is incorrect.

```{=latex}
\newpage
```

### Problem 4.2

_Explain why, when conditioning on selection for funding, there might be a negative correlation between rigor and impact even if there none generally exists._

Since both rigor and impact scores are drawn from a normally distributed population, there will be some proposals that score highly on both metrics, some that score poorly on both, some that score highly on one but not the other, and some that score near the mean on one or both. As such, the correlation between rigor and impact across any set of 200 funding proposals will depend on exactly how many proposals fall into the above categories; that is, it will look relatively random, explaining why @fig-correlation-all looks similar to a normal distribution. However, when controlling for only the top 10% of total scores in each set, the proposals that scored poorly on either metric are likely to be removed from the subset, leaving only proposals that did strongly on both or strongly on one and near-average on another. For most of these proposals, one metric performed better than the other, and so amongst the set of funded proposals, an increase in rigor appears to be correlated with a decrease in rigor and vice-versa. Thus, the correlation amongst funded proposals is likely to be negative, leading to the distribution in @fig-correlation-accepted.

```{=latex}
\newpage
```

# Problem 5 (5 points)

### Problem 5.1

_Derive and code a simulation model for the above interview procedure given a "true" probability of cheating $p$. Simulate your model (for a class of 100 students) 50,000 times under your hypothesis of 5% cheating, the TA's hypothesis of 30% cheating, and plot the resulting datasets._

```{julia}
#| echo: false
#| output: false
yes_counts_5 = []
for j = 1:50000
    ncheated = 0
    for i = 1:100
        cf1 = rand((1,2))
        if cf1 == 1 #Heads
            cheating = rand(1:20)
            if cheating == 20
                ncheated += 1
            end
        elseif cf1 == 2 #tails
            cf2 = rand((1,2))
            if cf2 == 1 #Heads
                ncheated += 1
            end
        end
    end
    append!(yes_counts_5, [ncheated])
end

yes_counts_30 = []
for j = 1:50000
    ncheated = 0
    for i = 1:100
        cf1 = rand((1,2))
        if cf1 == 1 #Heads
            cheating = rand(1:10)
            if cheating <= 3
                ncheated += 1
            end
        elseif cf1 == 2 #tails
            cf2 = rand((1,2))
            if cf2 == 1 #Heads
                ncheated += 1
            end
        end
    end
    append!(yes_counts_30, [ncheated])
end
```

```{julia}
#| echo: false
#| label: fig-cheating
#| fig-cap: "Histograms of cheating confession coin-flip method simulations. Top (blue) is under the Teacher's 5% cheating rate hypothesis, while bottom (orange) is under the TA's 30% cheating rate hypothesis."
p1 = plot(yes_counts_5, st=:histogram, legend=false, xlabel=""""Yes, I Cheated" Responses: 5% (Teacher) Hypothesis""", ylabel="Count", xlim=(0,60))
p2 = plot(yes_counts_30, st=:histogram, legend=false, xlabel=""""Yes, I Cheated" Responses: 30% (TA) Hypothesis""", ylabel="Count", color="orange", xlim=(0,60))
plot(p1, p2, layout=(2,1), suptitle="Simulation of Cheating Confessions")
```

### Problem 5.2
_How many "Yes, I cheated" answers do you think you'd need to see to feel confident concluding that the TA was right and why? You don't need to do a formal analysis, but can reason about this based on your plots._

Based on @fig-cheating, I would want to see at least 35 "Yes, I cheated" responses before concluding that the TA was right. At 35 Yes responses, there are a relatively low number of simulations from the 5% hypothesis, and a relatively high number from the 30% hypothesis. If I wanted to be even more confident in the TA's hypothesis, I would raise that number to 40 Yes responses, which very few simulations at the 5% level exceeded but roughly half of the simulations at the 30% level exceeded.